return {
  -- 'ray-x/navigator.lua',
  -- dependencies = {
  --   { 'hrsh7th/nvim-cmp' },
  --   { 'nvim-treesitter/nvim-treesitter' },
  --   { 'ray-x/guihua.lua', run = 'cd lua/fzy && make' },
  --   {
  --     'ray-x/go.nvim',
  --     event = { 'CmdlineEnter' },
  --     ft = { 'go', 'gomod' },
  --     build = ':lua require("go.install").update_all_sync()',
  --   },
  --   {
  --     'ray-x/lsp_signature.nvim', -- Show function signature when you type
  --     event = 'VeryLazy',
  --     config = function()
  --       require('lsp_signature').setup()
  --     end,
  --   },
  -- },
  -- config = function()
  --   require('navigator').setup {
  --     mason = true,
  --     lsp = {
  --       diagnostic_virtual_text = false,
  --       diagnostic = {
  --         underline = true,
  --         virtual_text = false, -- show virtual for diagnostic message
  --         update_in_insert = true, -- update diagnostic message in insert mode
  --         float = { -- setup for floating windows style
  --           focusable = true,
  --           sytle = 'minimal',
  --           border = 'rounded',
  --           source = 'always',
  --           header = '',
  --           prefix = '',
  --         },
  --       },
  --     },
  --   }
  -- end,
}
